version: '3'
services:
  front-app:
    image: front-app
    container_name: front-app
    ports:
      - 3000:3000
  go-app:
    image: go-app
    container_name: go-app
    ports:
      - 9090:9090
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.com
      - PGADMIN_DEFAULT_PASSWORD=4360
  postgres:
    image: postgres
    ports:
    - 5432:5432
    container_name: postgres
    environment:
    - POSTGRES_PASSWORD=4360
    volumes:
      - /tmp:/var/lib/postgresql/data


